# config/secrets.yml
defaults: &defaults
  secret_key_base: '4391b30b932d2ac1844351c4ef2c39c7f554173e9daa4ae9c3a596058fdac3057a9e4b9ec5d767bf187d87fe23bc7ba2b0f445e581620291b1e4313c8c50f9b4'
  support_email: 'support@graph-it.com'

secured: &secured
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults
  <<: *secured

production:
  <<: *defaults
  <<: *secured
